plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sh958022.selectiontoolbar'
    compileSdk 36

    defaultConfig {
        applicationId 'com.sh958022.selectiontoolbar'
        minSdk 26
        targetSdk 30
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly files('libs/xposed-api-stubs.jar')
}
